### ISSUE TITLE
[FEATURE] 디렉토리 구조 개편

### ISSUE THREAD

**Issue by kimjy97** [KNUT-Capstone-Design-team-1/wip-application-v2#11]
### 1. 개요 (한 줄로 간단하게 작성)
* 아토믹 디자인패턴 적용을 위한 기존 방식의 컴포넌트 디렉토리 구조를 개편
* 구분이 필요한 파일을 위한 디렉토리 추가

### 2. AS-IS (현재 상황 / 필요한 이유를 목록으로 작성)
* 현재 정리되지 않은 컴포넌트 디렉토리를 아토믹 디자인 패턴을 적용해 공통 컴포넌트들을 정의하고 효율적인 컴포넌트 개발과 관리가 가능하게 함

### 3. TO-BE (목표에 대해 목록으로 작성)
* 컴포넌트 디렉토리에 아토믹 패턴을 적용
  components
  ㄴ atoms
  ㄴ organisms
  ㄴ screens
* 구분이 필요한 파일을 위한 디렉토리 추가
  store
  ㄴ atoms
  ㄴ selectors
  api
  assets
  ㄴ images
  styles
  navigator
* 최상위 폴더 'src' 에 하위 디렉토리로 구성

### 4. 비고 (기타 사항)
*

**Comment by YongSiHun** [comment]
최대한 확장성이 좋은 패턴으로 하면 좋을 것 같습니다.
